INSERT INTO cidade (id, nome)
VALUES (1, 'Abadia de Goiás'),
       (2, 'Aparecida de Goiânia'),
       (3, 'Aragoiânia'),
       (4, 'Bela Vista de Goiás'),
       (5, 'Bonfinópolis'),
       (6, 'Brazabrantes'),
       (7, 'Caldazinha'),
       (8, 'Caturaí'),
       (9, 'Goiânia'),
       (10, 'Goianápolis'),
       (11, 'Goianira'),
       (12, 'Guapó'),
       (13, 'Hidrolândia'),
       (14, 'Inhumas'),
       (15, 'Nerópolis'),
       (16, 'Nova Veneza'),
       (17, 'Santo Antônio de Goiás'),
       (18, 'Senador Canedo'),
       (19, 'Terezópolis de Goiás'),
       (20, 'Trindade');
